Feat/55 england hockey fetcher
Martijn-van-Kekem-Development/hockey-match-calendar pull request #56
Opened 2024-08-18 16:53 UTC by philipohagan

Closes #55 

## Proposed Changes
- Added England Hockey Fetcher
- Change Match Title parser to support special characters
- Added support for mixed gender matches
TODO: Add specific club lookup list - hence draft PR until done

## Checklist

- [x] I have read the [contribution document](https://github.com/Martijn-van-Kekem-Development/hockey-match-calendar/blob/main/CONTRIBUTING.md).
- [x] I have added test cases to cover my changes (if applicable).
- [x] All new and existing test cases have passed.
- [x] My code adheres to the coding style of this project.

2024-08-18 17:50 UTC, martijnvankekem commented
Hi Philip, your PR triggered me to do some code refactoring, by replacing the gender types by enums. I just merged that to main.

Could you adjust your PR to include these changes?

2024-08-18 22:09 UTC, martijnvankekem commented
You're probably not going to like me, but the long lines drove me nuts when doing side-by-side comparisons, so I have strengthened the linter settings which changed basically every file.

Apologies in advance!

2024-08-19 13:56 UTC, martijnvankekem requested changes
Hi Philip, I've added some comments on your PR. Could you review them please?

Thanks for your hard work!

2024-08-19 13:56 UTC, martijnvankekem commented on src/Utils/ICSCreator.ts
> +            return pathFriendly ? "mixed" : "mixed's";
This should be "mixed" independent of the pathFriendly boolean.

2024-08-19 13:56 UTC, martijnvankekem commented on src/Fetchers/TMSFetcher/TMSMatchFetcher.ts
This doesn't seem right. Does this actually run without errors for the EH fetcher?

This regex doesn't match empty groups for the home- and away playing team, so it should throw an error instead of not populating the result[1] and result[2] values.

2024-08-19 13:56 UTC, martijnvankekem commented on CONTRIBUTING.md
> +npm run test
`npm test` is a built-in command, so the run can be omitted here.

2024-08-19 13:56 UTC, martijnvankekem commented on CONTRIBUTING.md
> +npm run check-lint
Can you change this to `npm run check` to check for typescript errors as well? You could add that to the text above as well.

2024-08-19 14:14 UTC, philipohagan commented on src/Fetchers/TMSFetcher/TMSMatchFetcher.ts
Yes, you're correct - but somethings gone weird with git here as that wasn't the final one I tested with either. Regardless, replaced regex and it pulls successfully for all fetchers.

2024-08-19 14:23 UTC, martijnvankekem commented
Did you push all changes to the branch yet? Some of the comments you resolved haven't been updated in your latest commit :)

2024-08-19 14:27 UTC, philipohagan commented
Not yet, nope!

On Mon, Aug 19, 2024 at 3:23 PM Martijn van Kekem ***@***.***>
wrote:

> Did you push all changes to the branch yet? Some of the comments you
> resolved haven't been updated in your latest commit :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Martijn-van-Kekem-Development/hockey-match-calendar/pull/56#issuecomment-2296706669>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHGCELDJWVHOY554IKKHQETZSH5XFAVCNFSM6AAAAABMWQJYGOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJWG4YDMNRWHE>
> .
> You are receiving this because you authored the thread.Message ID:
> <Martijn-van-Kekem-Development/hockey-match-calendar/pull/56/c2296706669@
> github.com>
>

2024-09-18 15:22 UTC, martijnvankekem approved these changes
LGTM!

2024-09-18 15:22 UTC, merged